version: "3.3"
services:
  postgres-db:
    image: postgres:14.5
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/home/postgresql/data


